# Generated by Django 5.2.3 on 2025-07-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
